-- MySQL Script generated by MySQL Workbench
-- Tue May  5 00:22:18 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bike_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bike_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bike_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bike_db` ;

-- -----------------------------------------------------
-- Table `bike_db`.`bike_markers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bike_db`.`bike_markers` (
  `station_id` BIGINT NOT NULL,
  `station_name` TEXT NULL DEFAULT NULL,
  `gu` TEXT NULL DEFAULT NULL,
  `address` TEXT NULL DEFAULT NULL,
  `stationLatitude` DOUBLE NULL DEFAULT NULL,
  `stationLongitude` DOUBLE NULL DEFAULT NULL,
  `lcd_count` DOUBLE NULL DEFAULT NULL,
  `qr_count` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`station_id`),
  INDEX `idx_markers_station` (`station_id` ASC) VISIBLE,
  INDEX `idx_markers_station_v2` (`station_id` ASC) VISIBLE,
  INDEX `idx_markers_latlon` (`stationLatitude` ASC, `stationLongitude` ASC) VISIBLE,
  INDEX `idx_markers_latlon_v2` (`stationLatitude` ASC, `stationLongitude` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bike_db`.`bike_usage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bike_db`.`bike_usage` (
  `usage_id` BIGINT NOT NULL AUTO_INCREMENT,
  `station_id` BIGINT NULL DEFAULT NULL,
  `datetime` TEXT NULL DEFAULT NULL,
  `date` TEXT NULL DEFAULT NULL,
  `rental_count` BIGINT NULL DEFAULT NULL,
  `year` TEXT NULL DEFAULT NULL,
  `month` TEXT NULL DEFAULT NULL,
  `day` BIGINT NULL DEFAULT NULL,
  `district` TEXT NULL DEFAULT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  `is_snow` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`usage_id`),
  INDEX `station_id` (`station_id` ASC) VISIBLE,
  CONSTRAINT `bike_usage_ibfk_1`
    FOREIGN KEY (`station_id`)
    REFERENCES `bike_db`.`bike_markers` (`station_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bike_db`.`bike_usage_heatmap_cache`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bike_db`.`bike_usage_heatmap_cache` (
  `station_id` BIGINT NOT NULL,
  `station_name` VARCHAR(255) NULL DEFAULT NULL,
  `gu` VARCHAR(50) NULL DEFAULT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  `year` VARCHAR(4) NOT NULL,
  `month` VARCHAR(2) NOT NULL,
  `rental_count` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`station_id`, `year`, `month`),
  CONSTRAINT `bike_usage_heatmap_cache_ibfk_1`
    FOREIGN KEY (`station_id`)
    REFERENCES `bike_db`.`bike_markers` (`station_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
